
name: GitHub Action for Python
on:
  push: 
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Python3
      uses: actions/setup-python@v1
      with:
        python-version: 3.9
      
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Lint with Black
      run: black.--check -l 120
    - name: Test with unittest
      run: pytest tests
    - name: Check types with mypy
      run: mypy.--ignore-missing-imports
