name: Python-CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with: 
          python-version: 3.8.8
      
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
      - name: Lint with Black
        run: |
          black . --check -l 120
          
      - name: Test with pytest
        run: |
          if [ -d tests ]; then python -m pytest tests; fi
          
      - name: Check types with mypy
        run: |
          if [ -f *.py ]; then mypy . --ignore-missing-imports; fi
